workspaceLocation: "./next-gen-inscription/client/inscription-editor.code-workspace"
tasks:
  - name: Vite Dev Server
    init: yarn --cwd client
    command: yarn --cwd client standalone start:mock
  - command: gp ports await 3000 && gp preview $(gp url 3000)/mock.html
    openMode: split-right
ports:
  - port: 3000
    onOpen: notify
vscode:
  extensions:
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
