WebServiceClients:
  Personal Service:
    Id: 1610883FA3A6C2CB
    WsCallLibrary: CXF
  GeoIpService:
    Id: 160DF5320F0D7ACD
    WsdlUrl: http://www.webservicex.net/geoipservice.asmx?WSDL
    WsCallLibrary: CXF
    ServiceClass: net.webservicex.client.GeoIPService
    Endpoints:
      GeoIPServiceSoap:
        - http://www.webservicex.net/geoipservice.asmx
      GeoIPServiceSoap12:
        - http://www.webservicex.net/geoipservice.asmx
      GeoIPServiceHttpGet:
        - http://www.webservicex.net/geoipservice.asmx
      GeoIPServiceHttpPost:
        - http://www.webservicex.net/geoipservice.asmx
    Features:
      - ch.ivyteam.ivy.webservice.exec.cxf.feature.HttpBasicAuthenticationFeature
    Properties:
      username: bruno
      password: ${decrypt:\u00E8\u00BD\u0080\u007C\u0051\u0095\u00D1\u0071\u0070\u0047\u0072\u00B5\u00BC\u00E0\u004B\u00A9\u0003\u0040\u0034\u00D8\u0079\u00D0\u00F9\u0076\u009C\u00A1\u0031\u00DF\u005C\u001F\u008F\u00DA}
