export * from './name/NameTab';
export * from './OutputTab';
export * from './CodeTab';
export * from './StartTab';
export * from './ResultTab';
export * from './CaseTab';
export * from './task/TaskTab';
export * from './call/CallTab';
export * from './EndPageTab';
